### ISSUE TITLE
[折叠左侧导航栏的情况下，多标签的tab条会遮挡导航栏第一条导航] 

### ISSUE THREAD

**Issue by os7blue** [Tencent/tdesign-vue-starter#105]
### tdesign-vue-starter 版本

0.1.0

### 重现步骤

如题

### 框架版本

vue2

### 补充说明

![image](https://user-images.githubusercontent.com/33112372/163099829-226f1f44-114c-4435-8309-acf85b5a7f40.png)

**Comment by uyarn** [comment]
https://github.com/Tencent/tdesign-vue-starter/commit/2e39b1991d50435d09b901c2bdc29a926737511e 
zindex修改一下。
