### ISSUE TITLE
[路由以及导航栏] 

### ISSUE THREAD

**Issue by os7blue** [Tencent/tdesign-vue-starter#107]
### tdesign-vue-starter 版本

当前版本

### 重现步骤

通过源码发现，路由以及导航栏相关内容中meta中有一些自定义字段的应用，比如hidden这个，可以在文档中对相关字段进行说明

**Comment by uyarn** [comment]
https://tdesign.tencent.com/starter/docs/vue/router-menu 来了 谢谢反馈 
如果感兴趣可以加入TDesign starter的开发共建群呀~ https://tdesign.tencent.com/starter/docs/vue/join-us
