### ISSUE TITLE
[td-starter] 列表页菜单收起时，表头操作列错位

### ISSUE THREAD

**Issue by ccfjzf2022** [Tencent/tdesign-vue-starter#128]
### tdesign-vue-starter 版本

0.2.2

### 实际结果

![image](https://user-images.githubusercontent.com/77626468/170849038-4d7305c7-d46b-4449-a613-53c1a2a75157.png)

**Comment by uyarn** [comment]
@ccfjzf2022  这个问题已经修复了 升级一下组件库即可 如果还有问题 再reopen吧：）

Uploading Jun-30-2022 20-23-44.mp4…

**Comment by uyarn** [comment]
@ccfjzf2022 这个问题已经修复了 升级一下组件库即可 如果还有问题 再reopen吧：）

https://user-images.githubusercontent.com/26377630/176676357-7a428ff1-38aa-473c-aa25-f159eedb5c08.mp4
