### ISSUE TITLE
[td-starter Vue2] 页面created\mounted只会执行一次，是配置问题吗？

### ISSUE THREAD

**Issue by ccfjzf2022** [Tencent/tdesign-vue-starter#136]
### tdesign-vue-starter 版本

0.2.0？用td-starter init的项目在哪里看版本？

### 重现步骤

1. td-starter init 初始化项目
2. npm install
3. npm run dev
4. 列表页随便点，只有第一次点击的时候会请求后台接口数据
5. 在/src/pages/detail/base/index.vue中新增下面的代码，只会第一次点击进去的时候打印：
```javascript
  mounted() {
    console.log('detail/base/index/mounted')
  },
```
这里再次进去编辑时，会显示之前的数据，

### 框架版本

"vue": "^2.6.11",

### Node版本

12.19.0

**Comment by uyarn** [comment]
我确认一下 可能和多标签页有关系

**Comment by ccfjzf2022** [comment]
> 我确认一下 可能和多标签页有关系

测试时，页面配置没有勾选多标签页，如果不是bug麻烦在starter文档说明一下，文档我只看到了这个 `name 影响多标签 Tab 页的 keep-alive 的能力` 。

**Comment by uyarn** [comment]
@ccfjzf2022 需要保留多标签的能力吗 如果不需要 暂时把src/layouts/components/Content.vue的内容
```
<keep-alive :include="this.aliveViews">
      <router-view v-if="!this.isRefreshing" />
</keep-alive> 
```
改成
<router-view  />
