### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by xioker** [Tencent/tdesign-vue-starter#163]
### tdesign-vue-starter 版本

目前在本地项目可以

### 重现步骤

启动项目 安装依赖后 打开就各种报错
![image](https://user-images.githubusercontent.com/48112362/185059712-a474afbd-efbc-4db8-81f7-3368670f30fe.png)
![image](https://user-images.githubusercontent.com/48112362/185060182-1dba4029-2b6a-4cf9-98e1-6e2641d114e0.png)

### Node版本

14.15.1

### 补充说明

项目重新打开  安装依赖npm install后 启动项目就各种报错

**Comment by uyarn** [comment]
请问有改动TDesign的引入方式吗 我这边本地没有异常 看这个报错 是因为composition-api没有引入导致的
