### ISSUE TITLE
[菜单]菜单如何支持外部链接

### ISSUE THREAD

**Issue by litaohms** [Tencent/tdesign-vue-starter#173]
### 这个功能解决了什么问题

目前我们有系统嵌套的需求，想点击菜单，在中间区域打开另外一个系统的页面，请问如何能实现

### 你建议的方案是什么

谢谢

**Comment by uyarn** [comment]
https://tdesign.tencent.com/starter/docs/vue/router-menu
<img width="973" alt="image" src="https://user-images.githubusercontent.com/26377630/190300100-67864007-3a5b-497c-bfc3-848b2ef9e935.png">
文档有描述

**Comment by litaohms** [comment]
不跳转页面，只是在内容区打开如何处理？

**Comment by uyarn** [comment]
没理解你的意思？在内容区打开是指什么？

**Comment by weifengze** [comment]
他的意思是在layout区打开外链的页面
@litaohms 可以自己写一个InnerLink处理一下用iframe显示
