### ISSUE TITLE
Pagination 分页 table 隐藏页码失效

### ISSUE THREAD

**Issue by Fluox-Etine** [Tencent/tdesign-vue-starter#174]
### tdesign-vue-starter 版本

0.3.1

### 重现链接

no

### 重现步骤

   :data="data"
        :columns="columns"
        :rowKey="rowKey"
        :hover="true"
        :pagination="pagination"
        @page-change="rehandlePageChange"
        @change="rehandleChange"
        :showPageSize="false"
        :loading="dataLoading"
        :headerAffixedTop="true"

### 期望结果

设置了false  隐藏了一页多少条数据

### 实际结果

还是显示设置一页多少条数据

### 框架版本

Vue

**Comment by uyarn** [comment]
`showPageSize` 不是table的API 需要通过`pagination`这个API透传 即 
<img width="555" alt="image" src="https://user-images.githubusercontent.com/26377630/194684588-f35e0339-9931-4d75-9d51-0371e7cc2c25.png">

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/26377630/194684583-97a1d7ff-0a6e-430d-972e-ddad8e7453e2.png">

**Comment by uyarn** [comment]
如果还有疑问再打开这个issue 先close了。
