### ISSUE TITLE
[SideNav.vue] 开启tab选项卡之后配置三级菜单点击tab选项卡无法打开三级菜单问题

### ISSUE THREAD

**Issue by jiangzenong** [Tencent/tdesign-vue-starter#182]
### 这个功能解决了什么问题

defaultExpanded() {
      const path = this.active;
      const parentPath = path.substring(0, path.lastIndexOf("/"));
      if (parentPath.lastIndexOf("/")) {
        const Lv3 = parentPath.substring(0, parentPath.lastIndexOf("/"));
        return Lv3 === "" ? [] : [parentPath, Lv3];
      }
      return parentPath === "" ? [] : [parentPath];
    },

### 你建议的方案是什么

判断parentPath里是否是三级菜单路由，是三级菜单路由就再进行一次分割，并将二级菜单项和一级菜单项放置进defaultExpanded数组中

**Comment by jiangzenong** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by uyarn** [comment]
看起来已经有方案了 方便提个PR吗~
