### ISSUE TITLE
三级菜单按照官方配置 打不开 第三季页面

### ISSUE THREAD

**Issue by Fluox-Etine** [Tencent/tdesign-vue-starter#192]
### tdesign-vue-starter 版本

0.4.3

### 重现步骤

  {
    path: '/menu',
    name: 'menu',
    component: Layout,
    meta: { title: '一级菜单', icon: 'menu-fold' },
    children: [
      {
        path: 'second',
        meta: { title: '二级菜单' },
        component: () => import('@/layouts/setting.vue'),
        children: [
          {
            path: 'third',
            name: 'NestMenu',
            component: () => import('@/layouts/blank.vue'),
            meta: { title: '三级菜单' },
          },
        ],
      },
    ],
  }

### 期望结果

右边部分显示 三级菜单vue页面数据

### 实际结果

没反应

### 框架版本

~2.6.14

### 浏览器版本

 107.0.5304.107

### 系统版本

Windows 11

### Node版本

16

**Comment by uyarn** [comment]
https://github.com/Tencent/tdesign-vue-starter/pull/189 参考这个改动还是异常吗？

**Comment by Fluox-Etine** [comment]
> 对就是用户官方的例子  页面也是官方的例子；还是打不开的。我这边什么都没有改动的

**Comment by uyarn** [comment]
我看看哦

**Comment by uyarn** [comment]
参考 https://github.com/Tencent/tdesign-vue-starter/pull/196
