### ISSUE TITLE
[Layout] 全局布局下底部出现突兀的白边

### ISSUE THREAD

**Issue by simon1uo** [Tencent/tdesign-vue-starter#204]
### 重现链接
https://tdesign.tencent.com/starter/vue/#/dashboard/base

### 重现步骤
打开 TDesign Starter 相关的 Demo 即可重现？

### 期望结果
希望这个白边能够去掉 

### 实际结果
没有找到在哪里能调整这个布局的样式
![](https://i.328888.xyz/2022/12/15/yayoq.png)

| Environment | Info |
|---|---|
| 相关版本 | - |
| 框架版本 / 基础库版本 | Vue(2.6.10) |
| 系统、浏览器 | Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0) |
| Node版本 |  |

**Comment by simon1uo** [comment]
找到原因了：
![](https://i.328888.xyz/2022/12/15/yQ2b5.png)
大概是这里的 64px有点问题，我在自己的项目修改为56px（我这边的LayoutHeader的Height是56px）就解决了

**Comment by uyarn** [comment]
因为布局上头部和菜单都有个64->56的改变 这边没有同步 建议参考这个PR改动 https://github.com/Tencent/tdesign-vue-starter/pull/205
