### ISSUE TITLE
如何把vite打包构建快速修改为vue-cli打包构建

### ISSUE THREAD

**Issue by helloZmy** [Tencent/tdesign-vue-starter#224]
### 这个功能解决了什么问题

微前端方式嵌入tdesign-vue-starer项目，不支持vite打包构建的方式；
通过插件方式解决之后，存在体验问题；
如何把vite构建的项目，快速转换为vue-cli构建。

### 你建议的方案是什么

谢谢

**Comment by uyarn** [comment]
其实其他都是差不多的 区别可能只有比如svg使用的支持或者其他静态资源的加载的插件不一样.. 有试过直接把src的内容复制过去的效果吗
