### ISSUE TITLE
icon 无网络按需引入但是系统很多内置都是<t-icon 的比如菜单，这个要怎么按需啊

### ISSUE THREAD

**Issue by 15206125206** [Tencent/tdesign-vue-starter#233]
### 这个功能解决了什么问题

无网络环境icon加载图标

### 你建议的方案是什么

无网络环境也可以用 t-icon加载

**Comment by uyarn** [comment]
可以参考这里https://tdesign.tencent.com/vue-next/components/icon#t-icon%E3%80%81iconfont%E5%92%8Cicon%E4%BD%BF%E7%94%A8%E6%97%B6%E9%83%BD%E4%BC%9A%E5%8F%91%E8%B5%B7%E7%BD%91%E7%BB%9C%E8%AF%B7%E6%B1%82%EF%BC%8C%E6%88%91%E7%9A%84%E9%A1%B9%E7%9B%AE%E6%98%AF%E6%97%A0%E7%BD%91%E7%BB%9C%E5%9C%BA%E6%99%AF%EF%BC%8C%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%EF%BC%9F

**Comment by 15206125206** [comment]
参考了，但是如果菜单是后端获取的，后端该如何传icon这个属性啊

**Comment by uyarn** [comment]
那你可以升级到vite3.0以上 然后直接找node_modules里的 vue3的starter已经加了这个 vue2的我最近搬过来 你可以先参考这个代码 https://github.com/Tencent/tdesign-vue-next-starter/blob/develop/src/utils/route/index.ts#L14

**Comment by 15206125206** [comment]
好的谢谢
