### ISSUE TITLE
后台预览，浅色模式不能够使用深色导航

### ISSUE THREAD

**Issue by yxszz** [Tencent/tdesign-vue-starter#25]
**Describe Environment**

Add browser version here

**Describe the bug**

**Additional context**

**Comment by uyarn** [comment]
您好 可以自己配置menu的theme属性的
![image](https://user-images.githubusercontent.com/26377630/147216391-641655ed-04cb-412f-b807-48ee0e4251ce.png)

**Comment by yxszz** [comment]
好的，收到


从 Windows 版邮件发送

发件人: yuyang
发送时间: 2021年12月23日 17:06
收件人: Tencent/tdesign-vue-starter
抄送: yxszz; Author
主题: Re: [Tencent/tdesign-vue-starter] 后台预览，浅色模式不能够使用深色导航 (Issue #25)

您好 可以自己配置menu的theme属性的

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
