### ISSUE TITLE
cli创建vue2模板报错

### ISSUE THREAD

**Issue by rookielz** [Tencent/tdesign-vue-starter#26]
选择模板类型： 【Vue2】模板

× ❗错误：下载模板失败
❗错误信息： Error: 'git clone' failed with status 128

**Comment by uyarn** [comment]
您好 可以参考这里解决一下 
https://tdesign.tencent.com/starter/docs/feedback
![image](https://user-images.githubusercontent.com/26377630/147216574-ecb37cd1-dea6-466d-8dba-6ae42e33a581.png)

**Comment by uyarn** [comment]
@1166544 cli

**Comment by uyarn** [comment]
请重新install一下 tdesign-starter-cli
