### ISSUE TITLE
[Menu] Vue2.7 中使用Menu组件 点击报错

### ISSUE THREAD

**Issue by xiaoyi510** [Tencent/tdesign-vue-starter#265]
### tdesign-vue-starter 版本

最新

### 重现步骤

 // methods
    const handleClick = (e: MouseEvent) => {
      e.stopPropagation();
      if (props.disabled) return;
      menu.select(props.value);
      ctx.emit('click');

      if (props.href) {
        window.open(props.href, props.target);
      } else if (props.to) {
        const { proxy } = getCurrentInstance();
        const router = props.router || (proxy as Record<string, any>).$router;
        const methods: string = props.replace ? 'replace' : 'push';
        router[methods](props.to).catch((err: Error) => {
          // vue-router 3.1.0+ push/replace cause NavigationDuplicated error
          // https://github.com/vuejs/vue-router/issues/2872
          // 当前path和目标path相同时，会抛出NavigationDuplicated的错误
          if (
            err.name !== 'NavigationDuplicated'
            && !err.message.includes('Avoided redundant navigation to current location')
          ) {
            throw err;
          }
        });
      }

点击菜单会触发上面的方法
但是其中getCurrentInstance为null 无法使用

### 期望结果

可以正常点击

### 框架版本

vue 2.7

### 浏览器版本

Chome

### 系统版本

Macos 11

### Node版本

18

### 补充说明

package:

```   

 "tdesign-vue": "^1.5.0-naruto",

    "vue": "^2.7.14",
```

**Comment by uyarn** [comment]
1 issue is enough, duplicate of https://github.com/Tencent/tdesign-vue/issues/2633
