### ISSUE TITLE
[后台模版Vue3] 引入新的组件后报错: Uncaught TypeError: isFunction is not a function

### ISSUE THREAD

**Issue by Koiandrop** [Tencent/tdesign-vue-starter#273]
### tdesign-vue-starter 版本

v0.3.3

### 重现步骤

需求预览PDF,引入github上PDF库后,使用库内组件报错:Uncaught TypeError: isFunction is not a function,展示空白页,重启项目无效,需要删除锁和node包再次install方可恢复项目.该库在其他项目可正常使用(已测过)
![Snipaste_2023-08-15_13-59-39](https://github.com/Tencent/tdesign-vue-starter/assets/76771363/e461c9f4-09fc-4e8f-8e2a-b25d60a9088c)

### 期望结果

可以正常引入其他库组件

### Node版本

v16.15.1

**Comment by FFEverglow** [comment]
https://github.com/501351981/vue-office

**Comment by Zxxxxxl** [comment]
我怎么没看到Vue3的版本 只有vue2

**Comment by a1226207408** [comment]
引入[vue.draggable.next](https://github.com/SortableJS/vue.draggable.next)时报同样的错误。

**Comment by FFEverglow** [comment]
> 

有多个版本可以选择

**Comment by FFEverglow** [comment]
@Zxxxxxl  有多个版本可以选择

**Comment by mansai** [comment]
> https://github.com/501351981/vue-office

有解决吗？

**Comment by timi137137** [comment]
![image](https://github.com/user-attachments/assets/8d65cc6c-10b6-4b24-bea7-903bda81a37d)

**Comment by mansai** [comment]
按下图操作已解决
![image](https://github.com/user-attachments/assets/1559fb24-945c-4ccf-bb21-0b33ed704e86)
