### ISSUE TITLE
官网最新的版本考虑开源吗？

### ISSUE THREAD

**Issue by HankBass** [Tencent/tdesign-vue-starter#287]
### 这个功能解决了什么问题

目前GitHub和npm上面的版本应该都是旧的版本，官网上的新版本风格切换的转换流畅了很多，这个版本考虑开源吗？

### 你建议的方案是什么

考虑开源

**Comment by timi137137** [comment]
你指的是腾讯云主题吗？这个默认就是开源的，在主分支

**Comment by HankBass** [comment]
> 你指的是腾讯云主题吗？这个默认就是开源的，在主分支

不是的，目前官网实例里面的切换主题、切换配置的部分，和git上面最新代码是不同的，官网的效果明显更流畅，而且显示方式也不同，目前官网最新的版本还支持字体大小、padding等这些地方的设置，但是git下下来运行的在切换的时候有卡顿的感觉，也缺少了这些功能，应该是最新的版本并没有发布到git上

**Comment by uyarn** [comment]
在这个分支 https://github.com/Tencent/tdesign-vue-starter/tree/site 有需要clone下来然后checkout到site就有了 区别不大 只是这个部分对实际项目没有很大的意义 所以就没作为默认分支的一部分
