### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by InsHomePgup** [Tencent/tdesign-vue-starter#324]
### tdesign-vue-starter 版本

1.10.2

### 重现链接

https://github.com/InsHomePgup/tdesign-starter-devtools

### 重现步骤

仅仅是安装了devtools

### 期望结果

正常使用devtools

### 实际结果

启动以后就死循环了。。

**Comment by InsHomePgup** [comment]
拜托大佬们了，这个项目是我很好的学习资料，如果有devtools辅助学习的话，我可以更快掌握里面的知识点。不过现在我安装以后启动就死循环了= =不知道需要做什么改进可以正常使用。

**Comment by uyarn** [comment]
什么devtools?

**Comment by InsHomePgup** [comment]
https://devtools-next.vuejs.org/guide/vite-plugin

vue-devtools



> 什么devtools?
