### ISSUE TITLE
设置主题配置后, 不会生效

### ISSUE THREAD

**Issue by Anony-Dino** [Tencent/tdesign-vue-starter#35]
设置 src/config/style.ts 配置后, <html>标签不会加载 theme-mode 和 theme-color 属性

**Comment by uyarn** [comment]
标签是指哪里？

**Comment by Anony-Dino** [comment]
> 标签是指哪里？

HTML标签的 theme-mode 和 theme-color 属性

**Comment by uyarn** [comment]
已修复 谢谢反馈 如果之前项目有使用 可以大致按照这个PR改动同步https://github.com/Tencent/tdesign-vue-starter/pull/38
