### ISSUE TITLE
能否增加cdn的引用？

### ISSUE THREAD

**Issue by liugongxun** [Tencent/tdesign-vue-starter#37]
有的时候，只想在旧项目中，引用一下组件效果，不想cli。

**Comment by uyarn** [comment]
是需要组件库的CDN引用么？

**Comment by liugongxun** [comment]
是的


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: yuyang ***@***.***&gt;
发送时间: 2021年12月30日 11:45
收件人: Tencent/tdesign-vue-starter ***@***.***&gt;
抄送: liugongxun ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Tencent/tdesign-vue-starter] 能否增加cdn的引用？ (Issue #37)





 
是需要组件库的CDN引用么？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 94dreamer** [comment]
已解决，增加了CDN引入方式。
https://tdesign.tencent.com/vue/components/getting-started
