### ISSUE TITLE
能增加Table表头的吸顶功能吗？

### ISSUE THREAD

**Issue by liugongxun** [Tencent/tdesign-vue-starter#45]
目前大都采用设定表格高度的的固定表头做法，在不同屏幕分辩率下体验并不好。如果能再增加一个表头的吸顶功能，就完美了。

**Comment by chaishi** [comment]
收到，支持

**Comment by uyarn** [comment]
组件的feature request麻烦提到组件库的Repo中 这边主要请提starter相关的issue和feature request.

**Comment by uyarn** [comment]
move to https://github.com/Tencent/tdesign-vue/issues/216
