### ISSUE TITLE
错误信息： HTTPError: Response code 503 (Service Temporarily Unavailable)

### ISSUE THREAD

**Issue by chengxiao** [Tencent/tdesign-vue-starter#46]
*****************************
  _____   ____                 _                     ____    _                    _
 |_   _| |  _ \    ___   ___  (_)   __ _   _ __     / ___|  | |_    __ _   _ __  | |_    ___   _ __
   | |   | | | |  / _ \ / __| | |  / _` | | '_ \    \___ \  | __|  / _` | | '__| | __|  / _ \ | '__|
   | |   | |_| | |  __/ \__ \ | | | (_| | | | | |    ___) | | |_  | (_| | | |    | |_  |  __/ | |
   |_|   |____/   \___| |___/ |_|  \__, | |_| |_|   |____/   \__|  \__,_| |_|     \__|  \___| |_|
                                   |___/
*****************************

✔ 构建环境正常！

? 请输入项目名称： TestProject
? 请输入项目描述： test
? 选择模板类型： 【Vue2】模板

👉  开始构建，请稍侯.

✖ ❗错误：下载模板失败
❗错误信息： HTTPError: Response code 503 (Service Temporarily Unavailable)

**Comment by uyarn** [comment]
持续复现么？重试一下呢

**Comment by chengxiao** [comment]
❯ node -v
v16.13.2
❯ npm -v
8.1.2
❯ which npm
/usr/local/bin/npm
❯ which node
/usr/local/bin/node

**Comment by mikespook** [comment]
这个错误的主要问题是 downloadUrl 使用了 fastgit.org 的镜像服务，但是 fastgit 挂了，持续返回 503。只要将 downloadUrl 切换回正常的 github 的下载地址即可。也就是对 tdesign-starter-cli 中 [ CoreGitDownloader 的 14 行](https://github.com/Tencent/tdesign-starter-cli/blob/main/src/core/CoreGitDownloader.ts#L14) 和 [19 行](https://github.com/Tencent/tdesign-starter-cli/blob/main/src/core/CoreGitDownloader.ts#L19) 做如下修改（diff/patch）：

`14c14
<     downloadUrl: 'hub.fastgit.org:Tencent/tdesign-vue-starter#main'
---
>     downloadUrl: 'https://github.com:Tencent/tdesign-vue-starter#main'
19c19
<     downloadUrl: 'hub.fastgit.org:Tencent/tdesign-vue-next-starter#main'
---
>     downloadUrl: 'https://github.com:Tencent/tdesign-vue-next-starter#main'`

我觉得默认应该使用 github 的地址，然后增加一个镜像服务的选项。

**Comment by mikespook** [comment]
> > 这个错误的主要问题是 downloadUrl 使用了 fastgit.org 的镜像服务，但是 fastgit 挂了，持续返回 503。只要将 downloadUrl 切换回正常的 github 的下载地址即可。也就是对 tdesign-starter-cli 中 [ CoreGitDownloader 的 14 行](https://github.com/Tencent/tdesign-starter-cli/blob/main/src/core/CoreGitDownloader.ts#L14) 和 [19 行](https://github.com/Tencent/tdesign-starter-cli/blob/main/src/core/CoreGitDownloader.ts#L19) 做如下修改（diff/patch）：
> > ```
> > 14c14
> > <     downloadUrl: 'hub.fastgit.org:Tencent/tdesign-vue-starter#main'
> > ---
> > >     downloadUrl: 'https://github.com:Tencent/tdesign-vue-starter#main'
> > 19c19
> > <     downloadUrl: 'hub.fastgit.org:Tencent/tdesign-vue-next-starter#main'
> > ---
> > >     downloadUrl: 'https://github.com:Tencent/tdesign-vue-next-starter#main'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我觉得默认应该使用 github 的地址，然后增加一个镜像服务的选项。
> 
> @mikespook 默认使用github的地址 请求超时的人更多 所以又切到了fastgit 但是看起来还是有用户请求不了这个镜像的资源

看来 github 在国内受到的干扰很大。
不过  fastgit 本身不太稳定，我在海外也没办法正常使用，得修改 downloadUrl 回 github 才可以用。

我建议调整下载 repo 的方式。 比如打包 zip 的发布包发布到 CDN，并增加选项让用户可以选择是使用稳定版本（CDN zip 文件）或者去 repo 下载指定的版本。

**Comment by chengxiao** [comment]
> 这个错误的主要问题是 downloadUrl 使用了 fastgit.org 的镜像服务，但是 fastgit 挂了，持续返回 503。只要将 downloadUrl 切换回正常的 github 的下载地址即可。也就是对 tdesign-starter-cli 中 [ CoreGitDownloader 的 14 行](https://github.com/Tencent/tdesign-starter-cli/blob/main/src/core/CoreGitDownloader.ts#L14) 和 [19 行](https://github.com/Tencent/tdesign-starter-cli/blob/main/src/core/CoreGitDownloader.ts#L19) 做如下修改（diff/patch）：
> 
> ```
> 14c14
> <     downloadUrl: 'hub.fastgit.org:Tencent/tdesign-vue-starter#main'
> ---
> >     downloadUrl: 'https://github.com:Tencent/tdesign-vue-starter#main'
> 19c19
> <     downloadUrl: 'hub.fastgit.org:Tencent/tdesign-vue-next-starter#main'
> ---
> >     downloadUrl: 'https://github.com:Tencent/tdesign-vue-next-starter#main'
> ```
> 
> 我觉得默认应该使用 github 的地址，然后增加一个镜像服务的选项。

多谢，已解决

**Comment by uyarn** [comment]
> 

之前看fastgit是对部分europe的用户不太友好。确实看目前的情况还是要自己部署一份到CDN上 谢谢建议 马上来处理一下。

**Comment by uyarn** [comment]
> 

之前看fastgit是对部分europe的用户不太友好。确实看目前的情况还是要自己部署一份到CDN上 谢谢建议 马上来处理一下。

**Comment by whr2349** [comment]
我也这样子，这么多天了还不行吗？

**Comment by uyarn** [comment]
> 我也这样子，这么多天了还不行吗？

这周要发个新版本处理了，如果也遇到这个问题先直接clone吧。

**Comment by uyarn** [comment]
`npm install tdesign-starter-cli@latest-g` 新版本改善了这个问题 如果还有问题可以reopen it
