### ISSUE TITLE
TDesign Stater后台管理系统，点击退出登录时候，第一次非常慢，并且无法退出

### ISSUE THREAD

**Issue by tdesign-helper** [Tencent/tdesign-vue-starter#48]
TDesign Stater后台管理系统，点击退出登录时候，第一次非常慢，并且无法退出，还是在管理页面，只有点击第二次退出登录时候，才会跳转到登录页面

**Comment by 94dreamer** [comment]
![企业微信截图_16424962188672](https://user-images.githubusercontent.com/15634204/149904198-0528a6b4-a647-4b6d-8f47-afff51889765.png)

**Comment by uyarn** [comment]
没有复现。https://tdesign.tencent.com/starter/vue/
