### ISSUE TITLE
错误信息： RequestError: read ECONNRESET

### ISSUE THREAD

**Issue by Calvest** [Tencent/tdesign-vue-starter#53]
**Describe Environment**
Chrome: 版本 97.0.4692.99（正式版本） （64 位）

**Describe the bug**
构建项目时提示错误信息： RequestError: read ECONNRESET

**Additional context**
<img width="738" alt="ff76de010f4f4bd8bb6229f81fb1509" src="https://user-images.githubusercontent.com/53268471/150246242-10d7a3a6-5d63-47dc-be0b-68a0a801ff59.png">

**Comment by Tonyee** [comment]
![image](https://user-images.githubusercontent.com/15208312/150257614-8ef79e2d-fc69-4e07-b9a2-a9010dbba7df.png)
我也一样，奇奇怪怪

**Comment by Calvest** [comment]
> ![image](https://user-images.githubusercontent.com/15208312/150257614-8ef79e2d-fc69-4e07-b9a2-a9010dbba7df.png) 我也一样，奇奇怪怪

根据 #46 排查应该是 tdesign-starter-cli 中 downloadUrl 链接被墙了的原因，我是修改为 https://github.com:Tencent/tdesign-vue-starter#main 后并且命令行走代理才构建成功

**Comment by uyarn** [comment]
`npm install tdesign-starter-cli@latest-g` 新版本改善了这个问题 如果还有问题可以reopen it
