### ISSUE TITLE
混合模式--分割菜单的情况下，list 页面布局问题

### ISSUE THREAD

**Issue by QJBChou** [Tencent/tdesign-vue-starter#54]
**Describe Environment**

edge

**Describe the bug**
混合模式--分割菜单的情况下，list 页面 会出现滚动条。
![image](https://user-images.githubusercontent.com/38748326/150379663-ed0c0fa6-6804-4f3e-acea-24c97754c356.png)
![image](https://user-images.githubusercontent.com/38748326/150379734-a0d09c94-c51d-4611-bdc6-aeb381e88912.png)

**Comment by octopustail** [comment]
未能复现该问题呢。
可以提供一下：OS信息、浏览器的版本吗？

**Comment by QJBChou** [comment]
是因为table 设置了 fixed属性，再分割菜单模式下就会出现这样的问题。
![image](https://user-images.githubusercontent.com/38748326/158022337-1c1af52f-7ec7-49c7-98ad-25d2feed9c63.png)

Microsoft Edge
版本 99.0.1150.36 (正式版本) (64 位)
