### ISSUE TITLE
[router scrollBehavior无效] 点击页面切换时，新页面位置无法滚动到顶部

### ISSUE THREAD

**Issue by padipata** [Tencent/tdesign-vue-starter#87]
### tdesign-vue-starter 版本

"tdesign-vue-next": "0.9.4",

### 重现步骤

页面滚动到底部，切换新页面

### 期望结果

新页面能够配置切换置顶🔝

**Comment by uyarn** [comment]
是说切换页面，应该回到自动回到顶部吗？我没有复现“无法滚动到顶部"的操作呢

**Comment by padipata** [comment]
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/25943907/159637975-3e8de927-a874-42bd-bc98-d727e5691a8a.png">
