### ISSUE TITLE
[layouts-Header] 配置了一级路由点击进去后，导航栏没有选中效果

### ISSUE THREAD

**Issue by padipata** [Tencent/tdesign-vue-starter#88]
### tdesign-vue-starter 版本

"tdesign-vue-next": "0.9.4",

### 重现步骤

<img width="458" alt="image" src="https://user-images.githubusercontent.com/25943907/159617153-ca80a35c-b376-45e3-9ff5-a4c17222fc56.png">
配置了一级路由（single: true），点击进入该页面后，导航栏无选中效果
<img width="194" alt="image" src="https://user-images.githubusercontent.com/25943907/159617390-348e8a41-cfa9-495e-ad98-c43dc6b5e3a2.png">

### 期望结果

点击进入该页面后，对应的导航栏（无论几级），最外层都要有选中效果，不然无法分辨当前活动页

**Comment by uyarn** [comment]
谢谢反馈 我们处理一下 也欢迎提PR帮我们修复：）

**Comment by padipata** [comment]
没看到修复记录...

**Comment by AkkoSpace** [comment]
没有修复

**Comment by Summer-Shen** [comment]
领取这个 issue，感谢
