### ISSUE TITLE
[enxConfig] 增加全局语言包配置

### ISSUE THREAD

**Issue by cybrobin** [Tencent/tdesign-vue-starter#92]
### 这个功能解决了什么问题

支持多国语言， 可以快速切换语言包

### 你建议的方案是什么

全局配置，增加语言包管理，可以增加类似 switch 控制且支持在组件在页面上切换，类似皮肤切换。

不同国家语言的字体、字号、间距等的也是有所差异，若多支持个英文的字体样式，就更好了。

**Comment by uyarn** [comment]
https://github.com/Tencent/tdesign-vue-starter/pull/101
