### ISSUE TITLE
[输入框组件] 验证码输入框强制变成密码框

### ISSUE THREAD

**Issue by PurityChan** [Tencent/tdesign-vue-starter#93]
### tdesign-vue-starter 版本

0.2.0

### 重现步骤

打开官方tdesign-vue-starter登录页，
https://tdesign.tencent.com/starter/vue/#/login?redirect=%2Fdashboard%2Fbase

1. 选择“使用手机号登录”，输入验证码
2. 
<img width="318" alt="87c8eb08e0f8c765ee2023e8d8fa33f" src="https://user-images.githubusercontent.com/8343216/160743067-38e911fe-0126-4f9c-9142-69ab53c801d0.png">

### 期望结果

验证码输入框是普通输入框，可以看到输入的数值

### 实际结果

验证码的普通输入框强制变成了密码框，无法控制其type值

### 框架版本

Vue(2.6.11)

### 浏览器版本

Microsoft Edge 版本 99.0.1150.55 (正式版本) (64 位)

### 系统版本

Win10

**Comment by uyarn** [comment]
fix #94
